### ISSUE TITLE
登临意活动中新增的干员模型错误

### ISSUE THREAD

**Issue by KaiserWilheim** [isHarryh/Ark-Models#7]
令的新皮肤、林、截云等干员的模型出现错误。
具体表现为这样：
![image.png](https://s2.loli.net/2023/01/27/aCEUJwzAZMDqeuh.png)
在学校没法解包，谁来处理一下（

**Comment by isHarryh** [comment]
问题已确认，系 https://github.com/isHarryh/Ark-Models/commit/7ad70b6ac88798133c017626b14ffaa7c00b0d3f 更新的PNG未进行RGB/Alpha通道图合成。将在重新处理后修复，感谢您的关注。

**Comment by isHarryh** [comment]
已于 https://github.com/isHarryh/Ark-Models/commit/48a5db1903361a06db5b5f1a02b6a34fcdfb3bf6 更正该错误。
